# Generated by Django 5.2.5 on 2025-10-30 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('company', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyinfo')),
                ('supplier', models.ForeignKey(limit_choices_to={'client_type__in': ['Supplier', 'Both']}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='client.client')),
            ],
            options={
                'unique_together': {('company', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.CharField(default=18, max_length=10, validators=[django.core.validators.RegexValidator(message='Rate must be a whole number (digits only).', regex='^\\d+$')])),
                ('withholdingTax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('extraTax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('furtherTax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('fedPaid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_inv.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
