# Generated by Django 5.2.5 on 2025-10-30 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ntn', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='NTN/CNIC must be 7 or 13 digits.', regex='^\\d{7}$|^\\d{13}$')])),
                ('address', models.TextField()),
                ('registration_type', models.CharField(max_length=50)),
                ('province_code', models.IntegerField()),
                ('province_name', models.CharField(max_length=100)),
                ('client_type', models.CharField(choices=[('Buyer', 'Buyer'), ('Supplier', 'Supplier'), ('Both', 'Both')], default='Buyer', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyinfo')),
            ],
        ),
    ]
