# Generated by Django 5.2.5 on 2025-10-29 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province_code', models.CharField(max_length=100)),
                ('province_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('ntn', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='NTN/CNIC must be either 7 or 13 digits', regex='^\\d{7}$|^\\d{13}$')])),
                ('strn', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fbr_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
