# Generated by Django 5.2.5 on 2025-10-30 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('company', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('doc_type_id', models.IntegerField()),
                ('doc_type_description', models.CharField(max_length=100)),
                ('fbr_invoice_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fbr_dated', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='invoice_qr/')),
                ('is_sent', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(limit_choices_to={'client_type__in': ['Buyer', 'Both']}, on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoices', to='client.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyinfo')),
            ],
            options={
                'unique_together': {('company', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retailPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_id', models.CharField(blank=True, max_length=50, null=True)),
                ('salesTaxWithheldAtSource', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extraTax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('furtherTax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('sroScheduleNo', models.CharField(blank=True, max_length=250, null=True)),
                ('sro_schedule_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('fedPayable', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('saleType', models.IntegerField()),
                ('saleTypeDesc', models.CharField(max_length=255)),
                ('sroItemSerialNo', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale_inv.saleinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
