# Generated by Django 5.2.5 on 2025-12-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
