# Generated by Django 5.2.5 on 2025-12-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_inv', '0002_alter_saleinvoice_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='ignore_stock',
            field=models.BooleanField(default=False),
        ),
    ]
